// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.7.1
// source: rpc/taxi/service.proto

package taxi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Order_Status int32

const (
	Order_UNPAID Order_Status = 0
	Order_PAID   Order_Status = 1
)

// Enum value maps for Order_Status.
var (
	Order_Status_name = map[int32]string{
		0: "UNPAID",
		1: "PAID",
	}
	Order_Status_value = map[string]int32{
		"UNPAID": 0,
		"PAID":   1,
	}
)

func (x Order_Status) Enum() *Order_Status {
	p := new(Order_Status)
	*p = x
	return p
}

func (x Order_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_taxi_service_proto_enumTypes[0].Descriptor()
}

func (Order_Status) Type() protoreflect.EnumType {
	return &file_rpc_taxi_service_proto_enumTypes[0]
}

func (x Order_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order_Status.Descriptor instead.
func (Order_Status) EnumDescriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{12, 0}
}

type Order_PaymentMethod int32

const (
	Order_PAY_PER_USE Order_PaymentMethod = 0
	Order_API_KEY     Order_PaymentMethod = 1
	Order_ASSET       Order_PaymentMethod = 2
)

// Enum value maps for Order_PaymentMethod.
var (
	Order_PaymentMethod_name = map[int32]string{
		0: "PAY_PER_USE",
		1: "API_KEY",
		2: "ASSET",
	}
	Order_PaymentMethod_value = map[string]int32{
		"PAY_PER_USE": 0,
		"API_KEY":     1,
		"ASSET":       2,
	}
)

func (x Order_PaymentMethod) Enum() *Order_PaymentMethod {
	p := new(Order_PaymentMethod)
	*p = x
	return p
}

func (x Order_PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order_PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_taxi_service_proto_enumTypes[1].Descriptor()
}

func (Order_PaymentMethod) Type() protoreflect.EnumType {
	return &file_rpc_taxi_service_proto_enumTypes[1]
}

func (x Order_PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order_PaymentMethod.Descriptor instead.
func (Order_PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{12, 1}
}

type TopupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TopupRequest) Reset() {
	*x = TopupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupRequest) ProtoMessage() {}

func (x *TopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupRequest.ProtoReflect.Descriptor instead.
func (*TopupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{0}
}

type TopupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TopupReply) Reset() {
	*x = TopupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupReply) ProtoMessage() {}

func (x *TopupReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupReply.ProtoReflect.Descriptor instead.
func (*TopupReply) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{1}
}

type GetTopupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *GetTopupRequest) Reset() {
	*x = GetTopupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopupRequest) ProtoMessage() {}

func (x *GetTopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopupRequest.ProtoReflect.Descriptor instead.
func (*GetTopupRequest) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopupRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetTopupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *GetTopupReply) Reset() {
	*x = GetTopupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopupReply) ProtoMessage() {}

func (x *GetTopupReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopupReply.ProtoReflect.Descriptor instead.
func (*GetTopupReply) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopupReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type TopupWithKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TopupWithKeyRequest) Reset() {
	*x = TopupWithKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupWithKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWithKeyRequest) ProtoMessage() {}

func (x *TopupWithKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWithKeyRequest.ProtoReflect.Descriptor instead.
func (*TopupWithKeyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{4}
}

type TopupWithKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TopupWithKeyReply) Reset() {
	*x = TopupWithKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupWithKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWithKeyReply) ProtoMessage() {}

func (x *TopupWithKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWithKeyReply.ProtoReflect.Descriptor instead.
func (*TopupWithKeyReply) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{5}
}

type GetAssetEstimateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unsigned  *Unsigned `protobuf:"bytes,1,opt,name=unsigned,proto3" json:"unsigned,omitempty"`
	AssetHash string    `protobuf:"bytes,2,opt,name=asset_hash,json=assetHash,proto3" json:"asset_hash,omitempty"`
}

func (x *GetAssetEstimateRequest) Reset() {
	*x = GetAssetEstimateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetEstimateRequest) ProtoMessage() {}

func (x *GetAssetEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetEstimateRequest.ProtoReflect.Descriptor instead.
func (*GetAssetEstimateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetEstimateRequest) GetUnsigned() *Unsigned {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *GetAssetEstimateRequest) GetAssetHash() string {
	if x != nil {
		return x.AssetHash
	}
	return ""
}

type GetAssetEstimateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Breakdown   *Breakdown `protobuf:"bytes,1,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	AssetAmount uint64     `protobuf:"varint,2,opt,name=asset_amount,json=assetAmount,proto3" json:"asset_amount,omitempty"`
	AssetHash   string     `protobuf:"bytes,3,opt,name=asset_hash,json=assetHash,proto3" json:"asset_hash,omitempty"`
	OrderId     string     `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *GetAssetEstimateReply) Reset() {
	*x = GetAssetEstimateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetEstimateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetEstimateReply) ProtoMessage() {}

func (x *GetAssetEstimateReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetEstimateReply.ProtoReflect.Descriptor instead.
func (*GetAssetEstimateReply) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetEstimateReply) GetBreakdown() *Breakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *GetAssetEstimateReply) GetAssetAmount() uint64 {
	if x != nil {
		return x.AssetAmount
	}
	return 0
}

func (x *GetAssetEstimateReply) GetAssetHash() string {
	if x != nil {
		return x.AssetHash
	}
	return ""
}

func (x *GetAssetEstimateReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type TopupWithAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unsigned  *Unsigned `protobuf:"bytes,1,opt,name=unsigned,proto3" json:"unsigned,omitempty"`
	AssetHash string    `protobuf:"bytes,2,opt,name=asset_hash,json=assetHash,proto3" json:"asset_hash,omitempty"`
	OrderId   string    `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *TopupWithAssetRequest) Reset() {
	*x = TopupWithAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupWithAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWithAssetRequest) ProtoMessage() {}

func (x *TopupWithAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWithAssetRequest.ProtoReflect.Descriptor instead.
func (*TopupWithAssetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{8}
}

func (x *TopupWithAssetRequest) GetUnsigned() *Unsigned {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *TopupWithAssetRequest) GetAssetHash() string {
	if x != nil {
		return x.AssetHash
	}
	return ""
}

func (x *TopupWithAssetRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type TopupWithAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order       *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	AssetAmount uint64 `protobuf:"varint,2,opt,name=asset_amount,json=assetAmount,proto3" json:"asset_amount,omitempty"`
	AssetHash   string `protobuf:"bytes,3,opt,name=asset_hash,json=assetHash,proto3" json:"asset_hash,omitempty"`
	Expiry      uint64 `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *TopupWithAssetReply) Reset() {
	*x = TopupWithAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopupWithAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWithAssetReply) ProtoMessage() {}

func (x *TopupWithAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWithAssetReply.ProtoReflect.Descriptor instead.
func (*TopupWithAssetReply) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{9}
}

func (x *TopupWithAssetReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *TopupWithAssetReply) GetAssetAmount() uint64 {
	if x != nil {
		return x.AssetAmount
	}
	return 0
}

func (x *TopupWithAssetReply) GetAssetHash() string {
	if x != nil {
		return x.AssetHash
	}
	return ""
}

func (x *TopupWithAssetReply) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type Unsigned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pset       string  `protobuf:"bytes,1,opt,name=pset,proto3" json:"pset,omitempty"`
	SatPerByte float32 `protobuf:"fixed32,2,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"` // default 0.1
}

func (x *Unsigned) Reset() {
	*x = Unsigned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unsigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsigned) ProtoMessage() {}

func (x *Unsigned) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsigned.ProtoReflect.Descriptor instead.
func (*Unsigned) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{10}
}

func (x *Unsigned) GetPset() string {
	if x != nil {
		return x.Pset
	}
	return ""
}

func (x *Unsigned) GetSatPerByte() float32 {
	if x != nil {
		return x.SatPerByte
	}
	return 0
}

type PartialWithFees struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pset string `protobuf:"bytes,1,opt,name=pset,proto3" json:"pset,omitempty"`
}

func (x *PartialWithFees) Reset() {
	*x = PartialWithFees{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialWithFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialWithFees) ProtoMessage() {}

func (x *PartialWithFees) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialWithFees.ProtoReflect.Descriptor instead.
func (*PartialWithFees) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{11}
}

func (x *PartialWithFees) GetPset() string {
	if x != nil {
		return x.Pset
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string       `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status      Order_Status `protobuf:"varint,2,opt,name=status,proto3,enum=vulpemventures.liquid_taxi.taxi.Order_Status" json:"status,omitempty"`
	IsCompleted bool         `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	Unsigned    *Unsigned    `protobuf:"bytes,4,opt,name=unsigned,proto3" json:"unsigned,omitempty"`
	Breakdown   *Breakdown   `protobuf:"bytes,5,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	// This is the pset with fees
	Partial     *PartialWithFees    `protobuf:"bytes,6,opt,name=partial,proto3" json:"partial,omitempty"`
	CreatedAt   int64               `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Method      Order_PaymentMethod `protobuf:"varint,8,opt,name=method,proto3,enum=vulpemventures.liquid_taxi.taxi.Order_PaymentMethod" json:"method,omitempty"`
	AssetAmount uint64              `protobuf:"varint,9,opt,name=asset_amount,json=assetAmount,proto3" json:"asset_amount,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{12}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetStatus() Order_Status {
	if x != nil {
		return x.Status
	}
	return Order_UNPAID
}

func (x *Order) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Order) GetUnsigned() *Unsigned {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *Order) GetBreakdown() *Breakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *Order) GetPartial() *PartialWithFees {
	if x != nil {
		return x.Partial
	}
	return nil
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetMethod() Order_PaymentMethod {
	if x != nil {
		return x.Method
	}
	return Order_PAY_PER_USE
}

func (x *Order) GetAssetAmount() uint64 {
	if x != nil {
		return x.AssetAmount
	}
	return 0
}

type Breakdown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size       uint64  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	SatPerByte float32 `protobuf:"fixed32,2,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"` // default 0.1
	Fee        uint64  `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Rate       float32 `protobuf:"fixed32,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Spread     uint64  `protobuf:"varint,5,opt,name=spread,proto3" json:"spread,omitempty"`
	Total      uint64  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *Breakdown) Reset() {
	*x = Breakdown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_taxi_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Breakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Breakdown) ProtoMessage() {}

func (x *Breakdown) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_taxi_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Breakdown.ProtoReflect.Descriptor instead.
func (*Breakdown) Descriptor() ([]byte, []int) {
	return file_rpc_taxi_service_proto_rawDescGZIP(), []int{13}
}

func (x *Breakdown) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Breakdown) GetSatPerByte() float32 {
	if x != nil {
		return x.SatPerByte
	}
	return 0
}

func (x *Breakdown) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Breakdown) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Breakdown) GetSpread() uint64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *Breakdown) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_rpc_taxi_service_proto protoreflect.FileDescriptor

var file_rpc_taxi_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x78, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d,
	0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f,
	0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x22, 0x0e, 0x0a, 0x0c, 0x54, 0x6f, 0x70,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x54, 0x6f, 0x70,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x70, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x75,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65,
	0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61,
	0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74,
	0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x54,
	0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x7f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x75,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c,
	0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e,
	0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x22, 0xbe, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x45, 0x73,
	0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x09, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69,
	0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x09, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x15, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x08,
	0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69,
	0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xad, 0x01,
	0x0a, 0x13, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78,
	0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x40, 0x0a,
	0x08, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x73, 0x61, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x61, 0x74, 0x50, 0x65, 0x72, 0x42, 0x79, 0x74, 0x65, 0x22,
	0x25, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x46, 0x65,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x73, 0x65, 0x74, 0x22, 0xd3, 0x04, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x76, 0x75,
	0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d,
	0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f,
	0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x52, 0x08, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x48, 0x0a, 0x09,
	0x62, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78,
	0x69, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x09, 0x62, 0x72, 0x65,
	0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x4a, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d,
	0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f,
	0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x57, 0x69, 0x74, 0x68, 0x46, 0x65, 0x65, 0x73, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x4c, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x34, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74,
	0x61, 0x78, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x4e, 0x50, 0x41, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x49, 0x44,
	0x10, 0x01, 0x22, 0x38, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x41, 0x59, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x55,
	0x53, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x50, 0x49, 0x5f, 0x4b, 0x45, 0x59, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x53, 0x53, 0x45, 0x54, 0x10, 0x02, 0x22, 0x95, 0x01, 0x0a,
	0x09, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x20,
	0x0a, 0x0c, 0x73, 0x61, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x61, 0x74, 0x50, 0x65, 0x72, 0x42, 0x79, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66,
	0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x32, 0xda, 0x04, 0x0a, 0x04, 0x54, 0x61, 0x78, 0x69, 0x12, 0x63, 0x0a,
	0x05, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x12, 0x2d, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76,
	0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74,
	0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65,
	0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61,
	0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x12, 0x30,
	0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61,
	0x78, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x78, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79,
	0x12, 0x34, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61,
	0x78, 0x69, 0x2e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76,
	0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74,
	0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69,
	0x74, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x84, 0x01, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x12,
	0x38, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x76, 0x75, 0x6c, 0x70,
	0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69,
	0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x7e, 0x0a, 0x0e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x12, 0x36, 0x2e, 0x76, 0x75, 0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69,
	0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x54, 0x6f, 0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x76, 0x75,
	0x6c, 0x70, 0x65, 0x6d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x6c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x74, 0x61, 0x78, 0x69, 0x2e, 0x54, 0x6f,
	0x70, 0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x0a, 0x5a, 0x08, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x78, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_taxi_service_proto_rawDescOnce sync.Once
	file_rpc_taxi_service_proto_rawDescData = file_rpc_taxi_service_proto_rawDesc
)

func file_rpc_taxi_service_proto_rawDescGZIP() []byte {
	file_rpc_taxi_service_proto_rawDescOnce.Do(func() {
		file_rpc_taxi_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_taxi_service_proto_rawDescData)
	})
	return file_rpc_taxi_service_proto_rawDescData
}

var file_rpc_taxi_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_taxi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_taxi_service_proto_goTypes = []interface{}{
	(Order_Status)(0),               // 0: vulpemventures.liquid_taxi.taxi.Order.Status
	(Order_PaymentMethod)(0),        // 1: vulpemventures.liquid_taxi.taxi.Order.PaymentMethod
	(*TopupRequest)(nil),            // 2: vulpemventures.liquid_taxi.taxi.TopupRequest
	(*TopupReply)(nil),              // 3: vulpemventures.liquid_taxi.taxi.TopupReply
	(*GetTopupRequest)(nil),         // 4: vulpemventures.liquid_taxi.taxi.GetTopupRequest
	(*GetTopupReply)(nil),           // 5: vulpemventures.liquid_taxi.taxi.GetTopupReply
	(*TopupWithKeyRequest)(nil),     // 6: vulpemventures.liquid_taxi.taxi.TopupWithKeyRequest
	(*TopupWithKeyReply)(nil),       // 7: vulpemventures.liquid_taxi.taxi.TopupWithKeyReply
	(*GetAssetEstimateRequest)(nil), // 8: vulpemventures.liquid_taxi.taxi.GetAssetEstimateRequest
	(*GetAssetEstimateReply)(nil),   // 9: vulpemventures.liquid_taxi.taxi.GetAssetEstimateReply
	(*TopupWithAssetRequest)(nil),   // 10: vulpemventures.liquid_taxi.taxi.TopupWithAssetRequest
	(*TopupWithAssetReply)(nil),     // 11: vulpemventures.liquid_taxi.taxi.TopupWithAssetReply
	(*Unsigned)(nil),                // 12: vulpemventures.liquid_taxi.taxi.Unsigned
	(*PartialWithFees)(nil),         // 13: vulpemventures.liquid_taxi.taxi.PartialWithFees
	(*Order)(nil),                   // 14: vulpemventures.liquid_taxi.taxi.Order
	(*Breakdown)(nil),               // 15: vulpemventures.liquid_taxi.taxi.Breakdown
}
var file_rpc_taxi_service_proto_depIdxs = []int32{
	14, // 0: vulpemventures.liquid_taxi.taxi.GetTopupReply.order:type_name -> vulpemventures.liquid_taxi.taxi.Order
	12, // 1: vulpemventures.liquid_taxi.taxi.GetAssetEstimateRequest.unsigned:type_name -> vulpemventures.liquid_taxi.taxi.Unsigned
	15, // 2: vulpemventures.liquid_taxi.taxi.GetAssetEstimateReply.breakdown:type_name -> vulpemventures.liquid_taxi.taxi.Breakdown
	12, // 3: vulpemventures.liquid_taxi.taxi.TopupWithAssetRequest.unsigned:type_name -> vulpemventures.liquid_taxi.taxi.Unsigned
	14, // 4: vulpemventures.liquid_taxi.taxi.TopupWithAssetReply.order:type_name -> vulpemventures.liquid_taxi.taxi.Order
	0,  // 5: vulpemventures.liquid_taxi.taxi.Order.status:type_name -> vulpemventures.liquid_taxi.taxi.Order.Status
	12, // 6: vulpemventures.liquid_taxi.taxi.Order.unsigned:type_name -> vulpemventures.liquid_taxi.taxi.Unsigned
	15, // 7: vulpemventures.liquid_taxi.taxi.Order.breakdown:type_name -> vulpemventures.liquid_taxi.taxi.Breakdown
	13, // 8: vulpemventures.liquid_taxi.taxi.Order.partial:type_name -> vulpemventures.liquid_taxi.taxi.PartialWithFees
	1,  // 9: vulpemventures.liquid_taxi.taxi.Order.method:type_name -> vulpemventures.liquid_taxi.taxi.Order.PaymentMethod
	2,  // 10: vulpemventures.liquid_taxi.taxi.Taxi.Topup:input_type -> vulpemventures.liquid_taxi.taxi.TopupRequest
	4,  // 11: vulpemventures.liquid_taxi.taxi.Taxi.GetTopup:input_type -> vulpemventures.liquid_taxi.taxi.GetTopupRequest
	6,  // 12: vulpemventures.liquid_taxi.taxi.Taxi.TopupWithKey:input_type -> vulpemventures.liquid_taxi.taxi.TopupWithKeyRequest
	8,  // 13: vulpemventures.liquid_taxi.taxi.Taxi.GetAssetEstimate:input_type -> vulpemventures.liquid_taxi.taxi.GetAssetEstimateRequest
	10, // 14: vulpemventures.liquid_taxi.taxi.Taxi.TopupWithAsset:input_type -> vulpemventures.liquid_taxi.taxi.TopupWithAssetRequest
	3,  // 15: vulpemventures.liquid_taxi.taxi.Taxi.Topup:output_type -> vulpemventures.liquid_taxi.taxi.TopupReply
	5,  // 16: vulpemventures.liquid_taxi.taxi.Taxi.GetTopup:output_type -> vulpemventures.liquid_taxi.taxi.GetTopupReply
	7,  // 17: vulpemventures.liquid_taxi.taxi.Taxi.TopupWithKey:output_type -> vulpemventures.liquid_taxi.taxi.TopupWithKeyReply
	9,  // 18: vulpemventures.liquid_taxi.taxi.Taxi.GetAssetEstimate:output_type -> vulpemventures.liquid_taxi.taxi.GetAssetEstimateReply
	11, // 19: vulpemventures.liquid_taxi.taxi.Taxi.TopupWithAsset:output_type -> vulpemventures.liquid_taxi.taxi.TopupWithAssetReply
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_taxi_service_proto_init() }
func file_rpc_taxi_service_proto_init() {
	if File_rpc_taxi_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_taxi_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupWithKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupWithKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetEstimateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetEstimateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupWithAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopupWithAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unsigned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialWithFees); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_taxi_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Breakdown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_taxi_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_taxi_service_proto_goTypes,
		DependencyIndexes: file_rpc_taxi_service_proto_depIdxs,
		EnumInfos:         file_rpc_taxi_service_proto_enumTypes,
		MessageInfos:      file_rpc_taxi_service_proto_msgTypes,
	}.Build()
	File_rpc_taxi_service_proto = out.File
	file_rpc_taxi_service_proto_rawDesc = nil
	file_rpc_taxi_service_proto_goTypes = nil
	file_rpc_taxi_service_proto_depIdxs = nil
}
