#!/usr/bin/env bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

pushd $PARENT_PATH

mkdir -p ./generated/go/taxi
protoc \
  --go-grpc_out=paths=source_relative:./generated/go/taxi \
  --go_out=paths=source_relative:./generated/go/taxi \
  taxi.proto
popd
